nodeLinker: node-modules

npmAuthToken: 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

npmPublishRegistry: "https://npm.pkg.github.com"

npmRegistryServer: "https://registry.yarnpkg.com"

yarnPath: .yarn/releases/yarn-2.4.2.cjs
